# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2d2d8e9a1515abed66743be88782cacb6649b8659e847e23268d64e380d6643340430d3d490ffc29a75d221608e45eb68149311121a2ed8c44cb5916e968588

test:
  secret_key_base: 098f1450613b093f1c892b15c3cf75088b7b20c82dadbcb2eea03a43a38b84b2e5b1c6322aadd4542a5a922c85d7af67d7ec727547202ab5e3a8a00d25961764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
